import React, { useState } from 'react';
import { Box, Button, TextField, Dialog, DialogTitle, DialogContent, DialogActions, Table, TableBody, TableCell, TableHead, TableRow, IconButton, MenuItem, Paper, Typography, TableContainer, Chip, Card, CardContent, Grid, Autocomplete, InputAdornment, TablePagination, useTheme, useMediaQuery } from '@mui/material';
import { Add, Visibility, Delete, ReceiptLong, Search, Edit, Close } from '@mui/icons-material';
import { useData } from '../contexts/DataContext';

const Purchases = () => {
    const { purchases, vendors, inventory, addPurchase, updatePurchase, deletePurchase, categories, addInventoryItem, updateCategories } = useData();
    const [open, setOpen] = useState(false);
    const [viewPO, setViewPO] = useState(null);

    // Edit Mode State
    const [editMode, setEditMode] = useState(false);
    const [selectedPoId, setSelectedPoId] = useState(null);

    // Quick Add Product State
    const [quickAddOpen, setQuickAddOpen] = useState(false);
    const [activeRowIndex, setActiveRowIndex] = useState(null);
    const [newCategory, setNewCategory] = useState('');
    const [quickForm, setQuickForm] = useState({
        name: '', category: '', cost: '', price: '', productId: ''
    });

    // PO Form State
    const [vendorId, setVendorId] = useState('');
    const [status, setStatus] = useState('Ordered');
    const [poItems, setPoItems] = useState([{ productId: '', quantity: 1, cost: 0 }]);
    const [paymentStatus, setPaymentStatus] = useState('Unpaid');
    const [amountPaid, setAmountPaid] = useState(0);

    const theme = useTheme();
    const isMobile = useMediaQuery(theme.breakpoints.down('sm'));

    // Pagination State
    const [page, setPage] = useState(0);
    const [rowsPerPage, setRowsPerPage] = useState(10);

    const handleChangePage = (event, newPage) => {
        setPage(newPage);
    };

    const handleChangeRowsPerPage = (event) => {
        setRowsPerPage(parseInt(event.target.value, 10));
        setPage(0);
    };

    const handleOpen = (po = null) => {
        if (po) {
            setEditMode(true);
            setSelectedPoId(po.id);
            setVendorId(po.vendorId);
            setStatus(po.status);
            setPoItems(po.items.map(i => ({ productId: i.productId, quantity: i.quantity, cost: i.cost })));
            setPaymentStatus(po.paymentStatus);
            setAmountPaid(po.amountPaid);
        } else {
            setEditMode(false);
            setSelectedPoId(null);
            setVendorId('');
            setStatus('Ordered');
            setPoItems([{ productId: '', quantity: 1, cost: 0 }]);
            setPaymentStatus('Unpaid');
            setAmountPaid(0);
        }
        setOpen(true);
    };

    const handleQuickAddOpen = (index) => {
        setActiveRowIndex(index);
        setQuickForm({ name: '', category: '', cost: '', price: '', productId: '' });
        setQuickAddOpen(true);
    };

    const handleAddCategory = async () => {
        if (newCategory && !categories.includes(newCategory)) {
            const updated = [...categories, newCategory];
            await updateCategories(updated);
            setQuickForm({ ...quickForm, category: newCategory });
            setNewCategory('');
        }
    };

    const handleQuickSave = async () => {
        // Auto-generate ID if empty
        const id = quickForm.productId.trim() || `PRD-${Date.now()}`;
        const newItem = {
            ...quickForm,
            productId: id,
            price: parseFloat(quickForm.price) || 0,
            cost: parseFloat(quickForm.cost) || 0,
            quantity: 0, // Initial stock is 0 until PO is received
            supplier: vendors.find(v => v.id === vendorId)?.name || ''
        };

        await addInventoryItem(newItem);

        // Update PO Item with new product
        // We need to find the newly added item in inventory. Since inventory state might take a moment to sync,
        // we can assume it's valid and set the ID directly, or wait simpler: 
        // We just updated firestore, inventory syncs real-time. 
        // For immediate UI update, we can manually set the row's productId.
        // However, the Autocomplete options depend on `inventory`. 
        // Ideally we wait or optimistic update. Since `inventory` is from onSnapshot, it should be fast.
        // Let's manually set the row details.

        const updatedItems = [...poItems];
        if (activeRowIndex !== null) {
            // We need the ACTUAL document ID generated by addInventoryItem in DataContext.
            // DataContext's addInventoryItem generates `id` internally.
            // To be safe and precise, we should return ID from addInventoryItem.
            // But since we can generate our own doc ID if we want, let's modify addInventoryItem logic 
            // OR just match by productId.
            // Wait, `addInventoryItem` uses Date.now() as doc ID. 
            // We can't easily guess it.
            // Let's modify logic to rely on the fact that we just added it.
            // ACTUALLY, checking logic in DataContext: addInventoryItem generates `id` internally.
            // I will assume for now the user can search for it immediately after.
            // BETTER: Let's assume the user will search it.
            // OR: I can update poItems after a short timeout? No, that's flaky.
            // Simpler: Just close dialog and let user search.
            // User requested "automatically get added". 

            // TRICK: I can pass a preset ID to addInventoryItem if I modify DataContext, but I can't modify DataContext right now comfortably without risking breaking changes.
            // Let's just create it. The `inventory` list will update shortly.
        }
        setQuickAddOpen(false);
    };

    const handleAddItem = () => {
        setPoItems([...poItems, { productId: '', quantity: 1, cost: 0 }]);
    };

    const handleItemChange = (index, field, value) => {
        const updated = [...poItems];
        updated[index][field] = value;

        // Auto-fill cost if product selected
        if (field === 'productId') {
            const product = inventory.find(i => i.id === value);
            if (product) {
                updated[index].cost = product.cost || 0;
            }
        }
        setPoItems(updated);
    };

    const calculateTotal = () => {
        return poItems.reduce((sum, item) => sum + (item.quantity * item.cost), 0);
    };

    const handleSave = async () => {
        const total = calculateTotal();
        const poData = {
            vendorId,
            vendorName: vendors.find(v => v.id === vendorId)?.name || 'Unknown',
            status,
            paymentStatus,
            amountPaid: parseFloat(amountPaid) || 0,
            items: poItems.filter(i => i.productId),
            total,
            date: new Date().toISOString() // Or keep original date if editing? Usually date stays.
            // Simplified: New date for modify or keep old? Let's keep new date for now or we need to access old date.
            // If editing, we shouldn't change date ideally.
        };

        if (editMode && selectedPoId) {
            // Find old PO to pass for stock reversal logic if needed (handled in DataContext)
            const oldPo = purchases.find(p => p.id === selectedPoId);
            await updatePurchase(selectedPoId, { ...poData, date: oldPo.date }, oldPo);
        } else {
            await addPurchase(poData);
        }
        setOpen(false);
    };

    const handleDelete = async (id) => {
        if (window.confirm('Are you sure you want to delete this Purchase Order?')) {
            await deletePurchase(id);
        }
    };

    const handleReceiveStock = async (po) => {
        if (window.confirm(`Mark PO #${po.id} as Received? This will update inventory stock and mark it as Paid.`)) {
            await updatePurchase(po.id, {
                status: 'Received',
                paymentStatus: 'Paid',
                amountPaid: po.total
            }, po);
        }
    };

    return (
        <Box>
            <Box sx={{ mb: 4, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Box>
                    <Typography variant="h4" sx={{ fontWeight: 'bold', mb: 0.5 }}>Purchase Orders</Typography>
                    <Typography variant="body2" color="text.secondary">Track stock orders and vendor expenses</Typography>
                </Box>
                <Button variant="contained" startIcon={<Add />} onClick={() => handleOpen()} sx={{ borderRadius: 2, textTransform: 'none', fontWeight: 700, px: 3, background: 'linear-gradient(135deg, #1976d2 0%, #1565c0 100%)', boxShadow: '0 4px 12px rgba(25, 118, 210, 0.3)' }}>
                    Create Order
                </Button>
            </Box>

            <Grid container spacing={3} sx={{ mb: 4 }}>
                <Grid item xs={12} sm={4}>
                    <Card sx={{ borderRadius: 4, boxShadow: '0 4px 20px rgba(0,0,0,0.04)' }}>
                        <CardContent sx={{ p: 3, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                            <Box>
                                <Typography variant="caption" color="text.secondary" sx={{ fontWeight: 700 }}>Total Orders</Typography>
                                <Typography variant="h4" sx={{ fontWeight: 800, mt: 0.5 }}>{purchases.length}</Typography>
                            </Box>
                            <Box sx={{ p: 1.5, borderRadius: 3, bgcolor: 'rgba(25, 118, 210, 0.05)', color: 'primary.main' }}><ReceiptLong /></Box>
                        </CardContent>
                    </Card>
                </Grid>
                <Grid item xs={12} sm={4}>
                    <Card sx={{ borderRadius: 4, boxShadow: '0 4px 20px rgba(0,0,0,0.04)' }}>
                        <CardContent sx={{ p: 3, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                            <Box>
                                <Typography variant="caption" color="text.secondary" sx={{ fontWeight: 700 }}>Pending Delivery</Typography>
                                <Typography variant="h4" sx={{ fontWeight: 800, mt: 0.5, color: '#ed6c02' }}>
                                    {purchases.filter(p => p.status === 'Ordered').length}
                                </Typography>
                            </Box>
                            <Box sx={{ p: 1.5, borderRadius: 3, bgcolor: 'rgba(237, 108, 2, 0.05)', color: '#ed6c02' }}><ReceiptLong /></Box>
                        </CardContent>
                    </Card>
                </Grid>
                <Grid item xs={12} sm={4}>
                    <Card sx={{ borderRadius: 4, boxShadow: '0 4px 20px rgba(0,0,0,0.04)' }}>
                        <CardContent sx={{ p: 3, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                            <Box>
                                <Typography variant="caption" color="text.secondary" sx={{ fontWeight: 700 }}>Total Spent</Typography>
                                <Typography variant="h4" sx={{ fontWeight: 800, mt: 0.5, color: '#2e7d32' }}>
                                    ₹{purchases.reduce((sum, p) => sum + p.total, 0).toLocaleString()}
                                </Typography>
                            </Box>
                            <Box sx={{ p: 1.5, borderRadius: 3, bgcolor: 'rgba(46, 125, 50, 0.05)', color: '#2e7d32' }}><ReceiptLong /></Box>
                        </CardContent>
                    </Card>
                </Grid>
            </Grid>

            <Paper sx={{ borderRadius: 4, overflow: 'hidden', boxShadow: '0 4px 24px rgba(0,0,0,0.06)', border: '1px solid rgba(0,0,0,0.05)' }}>
                <TableContainer>
                    <Table>
                        <TableHead sx={{ bgcolor: 'rgba(25, 118, 210, 0.05)', borderBottom: '2px solid rgba(25, 118, 210, 0.1)' }}>
                            <TableRow>
                                <TableCell sx={{ fontWeight: 800, color: 'primary.main' }}>Date</TableCell>
                                <TableCell sx={{ fontWeight: 800, color: 'primary.main' }}>Vendor</TableCell>
                                <TableCell sx={{ fontWeight: 800, color: 'primary.main' }}>Items</TableCell>
                                <TableCell sx={{ fontWeight: 800, color: 'primary.main' }}>Total Cost</TableCell>
                                <TableCell sx={{ fontWeight: 800, color: 'primary.main' }}>Order Status</TableCell>
                                <TableCell sx={{ fontWeight: 800, color: 'primary.main' }}>Payment</TableCell>
                                <TableCell sx={{ fontWeight: 800, color: 'primary.main' }}>Actions</TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            {(rowsPerPage > 0
                                ? purchases.slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage)
                                : purchases
                            ).map((po) => (
                                <TableRow key={po.id} hover>
                                    <TableCell>
                                        <Typography variant="body2" fontWeight={600}>{new Date(po.date).toLocaleDateString()}</Typography>
                                        <Typography variant="caption" color="text.secondary">#{po.id.slice(-6)}</Typography>
                                    </TableCell>
                                    <TableCell>{po.vendorName}</TableCell>
                                    <TableCell>{po.items.length} Items</TableCell>
                                    <TableCell sx={{ fontWeight: 700 }}>₹{po.total.toLocaleString()}</TableCell>
                                    <TableCell>
                                        <Chip
                                            label={po.status}
                                            size="small"
                                            color={po.status === 'Received' ? 'success' : 'warning'}
                                            variant="outlined"
                                            sx={{ fontWeight: 700 }}
                                        />
                                    </TableCell>
                                    <TableCell>
                                        <Box>
                                            <Chip
                                                label={po.paymentStatus}
                                                size="small"
                                                sx={{
                                                    bgcolor: po.paymentStatus === 'Paid' ? 'rgba(46, 125, 50, 0.1)' : 'rgba(237, 108, 2, 0.1)',
                                                    color: po.paymentStatus === 'Paid' ? 'success.main' : 'warning.main',
                                                    fontWeight: 700,
                                                    mb: 0.5
                                                }}
                                            />
                                            {(po.paymentStatus === 'Paid' || po.paymentStatus === 'Partial') && (
                                                <Typography variant="caption" display="block" sx={{ fontWeight: 600 }}>
                                                    Paid: ₹{po.amountPaid?.toLocaleString()}
                                                </Typography>
                                            )}
                                        </Box>
                                    </TableCell>
                                    <TableCell>
                                        <Box sx={{ display: 'flex', gap: 0.5 }}>
                                            {/* <IconButton size="small"><Visibility fontSize="small" /></IconButton> */}
                                            {po.status === 'Ordered' && (
                                                <Button
                                                    size="small"
                                                    onClick={() => handleReceiveStock(po)}
                                                    sx={{ fontSize: '0.7rem', minWidth: 'auto', px: 1, mr: 1 }}
                                                    variant="outlined"
                                                    color="success"
                                                >
                                                    Receive
                                                </Button>
                                            )}
                                            <IconButton size="small" onClick={() => handleOpen(po)} sx={{ color: 'primary.main' }}>
                                                <Edit fontSize="small" />
                                            </IconButton>
                                            <IconButton size="small" onClick={() => handleDelete(po.id)} sx={{ color: 'error.main' }}>
                                                <Delete fontSize="small" />
                                            </IconButton>
                                        </Box>
                                    </TableCell>
                                </TableRow>
                            ))}
                            {purchases.length === 0 && (
                                <TableRow>
                                    <TableCell colSpan={7} align="center" sx={{ py: 8, color: 'text.secondary' }}>No purchase orders found.</TableCell>
                                </TableRow>
                            )}
                        </TableBody>
                    </Table>
                </TableContainer>
                <TablePagination
                    rowsPerPageOptions={[5, 10, 25]}
                    component="div"
                    count={purchases.length}
                    rowsPerPage={rowsPerPage}
                    page={page}
                    onPageChange={handleChangePage}
                    onRowsPerPageChange={handleChangeRowsPerPage}
                />
            </Paper>

            {/* Create/Edit PO Dialog */}
            <Dialog
                open={open}
                onClose={() => setOpen(false)}
                maxWidth="md"
                fullWidth
                fullScreen={isMobile}
                PaperProps={{ sx: { borderRadius: isMobile ? 0 : 4 } }}
            >
                <DialogTitle sx={{
                    bgcolor: 'primary.main',
                    color: 'white',
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center'
                }}>
                    <Typography variant="h6" sx={{ fontWeight: 800 }}>
                        {editMode ? 'Edit Purchase Order' : 'Create Purchase Order'}
                    </Typography>
                    {isMobile && (
                        <IconButton onClick={() => setOpen(false)} sx={{ color: 'white' }}>
                            <Close />
                        </IconButton>
                    )}
                </DialogTitle>
                <DialogContent sx={{ mt: 2, p: isMobile ? 2 : 3 }}>
                    <Box sx={{ mb: 3 }}>
                        <Typography variant="overline" color="text.secondary" sx={{ fontWeight: 800 }}>Vendor & Status</Typography>
                        <Grid container spacing={2} sx={{ mt: 0.5 }}>
                            <Grid item xs={12} sm={6}>
                                <Autocomplete
                                    options={vendors}
                                    getOptionLabel={(option) => option.name || ''}
                                    value={vendors.find(v => v.id === vendorId) || null}
                                    isOptionEqualToValue={(option, value) => option.id === value.id}
                                    onChange={(event, newValue) => {
                                        setVendorId(newValue ? newValue.id : '');
                                    }}
                                    disablePortal
                                    autoHighlight
                                    renderOption={(props, option) => (
                                        <Box component="li" {...props} key={option.id}>
                                            <Box>
                                                <Typography variant="body1" sx={{ fontWeight: 600 }}>{option.name}</Typography>
                                                <Typography variant="caption" color="text.secondary">{option.phone || 'No Phone'}</Typography>
                                            </Box>
                                        </Box>
                                    )}
                                    renderInput={(params) => (
                                        <TextField
                                            {...params}
                                            label="Search Vendor"
                                            fullWidth
                                            placeholder="Type vendor name..."
                                            helperText="Search by name or contact"
                                            variant="outlined"
                                        />
                                    )}
                                />
                            </Grid>
                            <Grid item xs={12} sm={6}>
                                <TextField
                                    select
                                    fullWidth
                                    label="Order Status"
                                    value={status}
                                    onChange={(e) => setStatus(e.target.value)}
                                >
                                    <MenuItem value="Ordered">Ordered (Pending)</MenuItem>
                                    <MenuItem value="Received">Received (Stock Added)</MenuItem>
                                </TextField>
                            </Grid>
                        </Grid>
                    </Box>

                    <Typography variant="overline" color="text.secondary" sx={{ fontWeight: 800 }}>Order Items</Typography>
                    {poItems.map((item, index) => (
                        <Paper
                            key={index}
                            elevation={0}
                            sx={{
                                p: 2,
                                mb: 2,
                                border: '1px solid',
                                borderColor: 'divider',
                                borderRadius: 2,
                                bgcolor: 'grey.50'
                            }}
                        >
                            <Grid container spacing={2} alignItems="center">
                                <Grid item xs={12} sm={5}>
                                    <Box sx={{ display: 'flex', gap: 1 }}>
                                        <Autocomplete
                                            fullWidth
                                            options={inventory}
                                            getOptionLabel={(option) => `${option.name} (Cost: ₹${option.cost || 0})`}
                                            value={inventory.find(i => i.id === item.productId) || null}
                                            isOptionEqualToValue={(option, value) => option.id === (typeof value === 'string' ? value : value?.id)}
                                            onChange={(e, newVal) => handleItemChange(index, 'productId', newVal?.id)}
                                            renderInput={(params) => <TextField {...params} label="Product" size="small" />}
                                        />
                                        <Button
                                            sx={{ minWidth: 40, px: 0 }}
                                            variant="contained"
                                            color="secondary"
                                            onClick={() => handleQuickAddOpen(index)}
                                            size="small"
                                        >
                                            <Add />
                                        </Button>
                                    </Box>
                                </Grid>
                                <Grid item xs={6} sm={3}>
                                    <TextField
                                        fullWidth
                                        label="Quantity"
                                        type="number"
                                        size="small"
                                        value={item.quantity}
                                        onChange={(e) => handleItemChange(index, 'quantity', parseInt(e.target.value))}
                                    />
                                </Grid>
                                <Grid item xs={6} sm={3}>
                                    <TextField
                                        fullWidth
                                        label="Buy Price"
                                        type="number"
                                        size="small"
                                        value={item.cost}
                                        onChange={(e) => handleItemChange(index, 'cost', parseFloat(e.target.value))}
                                        InputProps={{ startAdornment: <InputAdornment position="start">₹</InputAdornment> }}
                                    />
                                </Grid>
                                <Grid item xs={12} sm={1}>
                                    <IconButton
                                        color="error"
                                        onClick={() => setPoItems(poItems.filter((_, i) => i !== index))}
                                        size={isMobile ? 'medium' : 'small'}
                                        sx={{
                                            width: isMobile ? '100%' : 'auto',
                                            borderRadius: isMobile ? 1 : '50%',
                                            bgcolor: isMobile ? 'rgba(211, 47, 47, 0.04)' : 'transparent'
                                        }}
                                    >
                                        <Delete />
                                        {isMobile && <Typography variant="button" sx={{ ml: 1 }}>Remove</Typography>}
                                    </IconButton>
                                </Grid>
                            </Grid>
                        </Paper>
                    ))}

                    <Button
                        startIcon={<Add />}
                        onClick={handleAddItem}
                        variant="outlined"
                        fullWidth={isMobile}
                        sx={{ mb: 2 }}
                    >
                        Add Item
                    </Button>

                    <Box sx={{ mt: 3, p: 2, bgcolor: 'primary.main', color: 'white', borderRadius: 2 }}>
                        <Typography variant="overline" sx={{ fontWeight: 800, opacity: 0.9 }}>Payment Details</Typography>
                        <Grid container spacing={2} sx={{ mt: 0.5 }}>
                            <Grid item xs={12} sm={4}>
                                <TextField
                                    select
                                    fullWidth
                                    label="Payment Status"
                                    size="small"
                                    value={paymentStatus}
                                    onChange={(e) => setPaymentStatus(e.target.value)}
                                    sx={{ bgcolor: 'white', borderRadius: 1 }}
                                >
                                    <MenuItem value="Unpaid">Unpaid</MenuItem>
                                    <MenuItem value="Partial">Partial</MenuItem>
                                    <MenuItem value="Paid">Paid</MenuItem>
                                </TextField>
                            </Grid>
                            <Grid item xs={12} sm={4}>
                                <TextField
                                    fullWidth
                                    label="Paid Amount"
                                    type="number"
                                    size="small"
                                    value={amountPaid}
                                    onChange={(e) => setAmountPaid(e.target.value)}
                                    disabled={paymentStatus === 'Unpaid'}
                                    sx={{ bgcolor: 'white', borderRadius: 1 }}
                                />
                            </Grid>
                            <Grid item xs={12} sm={4} sx={{ display: 'flex', alignItems: 'center', justifyContent: { xs: 'flex-start', sm: 'flex-end' } }}>
                                <Box sx={{ textAlign: { xs: 'left', sm: 'right' } }}>
                                    <Typography variant="caption" sx={{ display: 'block', opacity: 0.8 }}>Total Order Value</Typography>
                                    <Typography variant="h5" sx={{ fontWeight: 800 }}>₹{calculateTotal().toLocaleString()}</Typography>
                                </Box>
                            </Grid>
                        </Grid>
                    </Box>
                </DialogContent>
                <DialogActions sx={{ p: 3 }}>
                    <Button onClick={() => setOpen(false)}>Cancel</Button>
                    <Button
                        onClick={handleSave}
                        variant="contained"
                        disabled={!vendorId}
                        sx={{ borderRadius: 2, px: 4, fontWeight: 700 }}
                    >
                        Save Order
                    </Button>
                </DialogActions>
            </Dialog>

            {/* Quick Add Product Dialog */}
            <Dialog open={quickAddOpen} onClose={() => setQuickAddOpen(false)} maxWidth="sm" fullWidth PaperProps={{ sx: { borderRadius: 4 } }}>
                <DialogTitle sx={{ bgcolor: 'secondary.main', color: 'white' }}>Quick Add Product</DialogTitle>
                <DialogContent sx={{ mt: 2 }}>
                    <TextField
                        fullWidth
                        label="Product ID"
                        value={quickForm.productId}
                        onChange={(e) => setQuickForm({ ...quickForm, productId: e.target.value })}
                        margin="normal"
                        helperText="Leave empty to auto-generate"
                        placeholder="e.g. SKU-1001"
                    />
                    <TextField
                        fullWidth
                        label="Product Name"
                        value={quickForm.name}
                        onChange={(e) => setQuickForm({ ...quickForm, name: e.target.value })}
                        margin="normal"
                    />
                    <TextField
                        select
                        fullWidth
                        label="Category"
                        value={quickForm.category}
                        onChange={(e) => setQuickForm({ ...quickForm, category: e.target.value })}
                        margin="normal"
                    >
                        {categories.map(cat => <MenuItem key={cat} value={cat}>{cat}</MenuItem>)}
                    </TextField>

                    <Box sx={{ display: 'flex', gap: 1, mt: 1, mb: 2 }}>
                        <TextField
                            size="small"
                            label="New Category"
                            value={newCategory}
                            onChange={(e) => setNewCategory(e.target.value)}
                            fullWidth
                        />
                        <Button onClick={handleAddCategory} variant="outlined" size="small">Add</Button>
                    </Box>

                    <Grid container spacing={2}>
                        <Grid item xs={6}>
                            <TextField
                                fullWidth
                                label="Cost Price (₹)"
                                type="number"
                                value={quickForm.cost}
                                onChange={(e) => setQuickForm({ ...quickForm, cost: e.target.value })}
                                margin="normal"
                                helperText="Your buying price"
                            />
                        </Grid>
                        <Grid item xs={6}>
                            <TextField
                                fullWidth
                                label="Selling Price (₹)"
                                type="number"
                                value={quickForm.price}
                                onChange={(e) => setQuickForm({ ...quickForm, price: e.target.value })}
                                margin="normal"
                                helperText="Price for customers"
                            />
                        </Grid>
                    </Grid>
                </DialogContent>
                <DialogActions sx={{ p: 3 }}>
                    <Button onClick={() => setQuickAddOpen(false)}>Cancel</Button>
                    <Button onClick={handleQuickSave} variant="contained" color="secondary" disabled={!quickForm.name || !quickForm.price}>Save & Add</Button>
                </DialogActions>
            </Dialog >
        </Box >
    );
};

export default Purchases;
